#ifndef UXB_SYMBOL_KIND_FBS
#define UXB_SYMBOL_KIND_FBS
Const SYM_VAR As String = "SYM_VAR"
Const SYM_CONST As String = "SYM_CONST"
Const SYM_PARAM As String = "SYM_PARAM"
Const SYM_FUNCTION As String = "SYM_FUNCTION"
Const SYM_SUB As String = "SYM_SUB"
Const SYM_TYPE As String = "SYM_TYPE"
Const SYM_TYPE_FIELD As String = "SYM_TYPE_FIELD"
Const SYM_CLASS As String = "SYM_CLASS"
Const SYM_CLASS_FIELD As String = "SYM_CLASS_FIELD"
Const SYM_CLASS_METHOD As String = "SYM_CLASS_METHOD"
Const SYM_INTERFACE As String = "SYM_INTERFACE"
Const SYM_ENUM As String = "SYM_ENUM"
Const SYM_MODULE As String = "SYM_MODULE"
Const SYM_NAMESPACE As String = "SYM_NAMESPACE"
Const SYM_ALIAS As String = "SYM_ALIAS"
Const SYM_IMPORT As String = "SYM_IMPORT"
Const SYM_LIBRARY As String = "SYM_LIBRARY"
Const SYM_LABEL As String = "SYM_LABEL"
Const SYM_FILE_HANDLE As String = "SYM_FILE_HANDLE"
Const SYM_RUNTIME_SERVICE As String = "SYM_RUNTIME_SERVICE"
#endif
