' Auto-generated by uxbdll 1.0.0.
' Source manifest: uxscalar_module.uxdll.json
' Do not edit by hand; regenerate from the manifest.

NAMESPACE uxscalar_module

CONST DLL_NAME = "uxscalar_module.dll"

FUNCTION uxscalar_init() AS I32
    RETURN CALL(DLL, "uxscalar_module.dll", "uxscalar_init", I32, CDECL)
END FUNCTION

FUNCTION uxscalar_add(leftValue AS I32, rightValue AS I32) AS I32
    RETURN CALL(DLL, "uxscalar_module.dll", "uxscalar_add", I32, CDECL, "I32,I32", leftValue, rightValue)
END FUNCTION

FUNCTION uxscalar_shutdown() AS I32
    RETURN CALL(DLL, "uxscalar_module.dll", "uxscalar_shutdown", I32, CDECL)
END FUNCTION

END NAMESPACE
