@echo off
setlocal EnableExtensions
pushd "%~dp0\..\.."
if errorlevel 1 exit /b 1
call "%~dp0interop\toolchain.env.bat"
if errorlevel 1 exit /b 1
"%UXB_LINK_CMD%" @%~dp0program_link_args.rsp -o "%~dp0uxgsl_basic_root_bisection_smoke.exe"
if errorlevel 1 (
  popd
  exit /b 1
)
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\uxcapi.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\uxcapi.dll" "%~dp0uxcapi.dll" >nul
if not exist "%~dp0uxcapi.dll" echo [x64-build] warning: FFI DLL not bundled: uxcapi.dll
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\uxgsl.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\uxgsl.dll" "%~dp0uxgsl.dll" >nul
if not exist "%~dp0uxgsl.dll" echo [x64-build] warning: FFI DLL not bundled: uxgsl.dll
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libgfortran-5.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libgfortran-5.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libgfortran-5.dll" "%~dp0libgfortran-5.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libquadmath-0.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libquadmath-0.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libquadmath-0.dll" "%~dp0libquadmath-0.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libopenblas.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libopenblas.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libopenblas.dll" "%~dp0libopenblas.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libffi-8.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libffi-8.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libffi-8.dll" "%~dp0libffi-8.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\libraries\bin\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxdataset\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx\lib\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxonnx2\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\dist\runtime_ext\deps\uxtensor\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\build\libraries\tests\abi10\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\tests\libraries\abi10\build\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if exist "native\uxb_runtime\build\uxb_runtime.dll" copy /Y "native\uxb_runtime\build\uxb_runtime.dll" "%~dp0uxb_runtime.dll" >nul
if not exist "%~dp0uxb_runtime.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\uxb_runtime.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\uxb_runtime.dll" "%~dp0uxb_runtime.dll" >nul
if not exist "%~dp0uxb_runtime.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\uxb_runtime.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\uxb_runtime.dll" "%~dp0uxb_runtime.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libwinpthread-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libwinpthread-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libwinpthread-1.dll" "%~dp0libwinpthread-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libuv-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libuv-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libuv-1.dll" "%~dp0libuv-1.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libtbb12.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libtbb12.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libtbb12.dll" "%~dp0libtbb12.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libgcc_s_seh-1.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libgcc_s_seh-1.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libgcc_s_seh-1.dll" "%~dp0libgcc_s_seh-1.dll" >nul
if not exist "%~dp0libstdc++-6.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libstdc++-6.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\native\uxb_runtime\build\libstdc++-6.dll" "%~dp0libstdc++-6.dll" >nul
if not exist "%~dp0libstdc++-6.dll" if exist "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libstdc++-6.dll" copy /Y "C:\Users\mete\Downloads\BasicOyunSource\UXBc_Clean\UXBc\uxb\bin\libstdc++-6.dll" "%~dp0libstdc++-6.dll" >nul
if not exist "%~dp0uxb_runtime.dll" (
  echo [x64-build] missing uxb_runtime.dll
  popd
  exit /b 1
)
echo [x64-build] link complete: %~dp0uxgsl_basic_root_bisection_smoke.exe
popd
exit /b 0
