/* uXBasic generated x64 FFI resolver */
#include <windows.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

extern void* __uxb_ffi_symptr_1;
extern void* __uxb_ffi_symptr_2;
extern void* __uxb_ffi_symptr_3;
extern void* __uxb_ffi_symptr_4;
extern void* __uxb_ffi_symptr_5;
extern void* __uxb_ffi_symptr_6;
extern void* __uxb_ffi_symptr_7;
extern void* __uxb_ffi_symptr_8;
extern void* __uxb_ffi_symptr_9;
extern void* __uxb_ffi_symptr_10;
extern void* __uxb_ffi_symptr_11;
extern void* __uxb_ffi_symptr_12;
extern void* __uxb_ffi_symptr_13;
extern void* __uxb_ffi_symptr_14;
extern void* __uxb_ffi_symptr_15;
extern void* __uxb_ffi_symptr_16;
extern void* __uxb_ffi_symptr_17;
extern void* __uxb_ffi_symptr_18;
extern void* __uxb_ffi_symptr_19;
extern void* __uxb_ffi_symptr_20;
extern void* __uxb_ffi_symptr_21;
extern void* __uxb_ffi_symptr_22;
extern void* __uxb_ffi_symptr_23;
extern void* __uxb_ffi_symptr_24;
extern void* __uxb_ffi_symptr_25;
extern void* __uxb_ffi_symptr_26;
extern void* __uxb_ffi_symptr_27;
extern void* __uxb_ffi_symptr_28;
extern void* __uxb_ffi_symptr_29;
extern void* __uxb_ffi_symptr_30;
extern void* __uxb_ffi_symptr_31;
extern void* __uxb_ffi_symptr_32;
extern void* __uxb_ffi_symptr_33;
extern void* __uxb_ffi_symptr_34;
extern void* __uxb_ffi_symptr_35;
extern void* __uxb_ffi_symptr_36;
extern void* __uxb_ffi_symptr_37;
extern void* __uxb_ffi_symptr_38;
extern void* __uxb_ffi_symptr_39;
extern void* __uxb_ffi_symptr_40;
extern void* __uxb_ffi_symptr_41;
extern void* __uxb_ffi_symptr_42;
extern void* __uxb_ffi_symptr_43;
extern void* __uxb_ffi_symptr_44;
extern void* __uxb_ffi_symptr_45;
extern void* __uxb_ffi_symptr_46;
extern void* __uxb_ffi_symptr_47;
extern void* __uxb_ffi_symptr_48;
extern void* __uxb_ffi_symptr_49;
extern void* __uxb_ffi_symptr_50;
extern void* __uxb_ffi_symptr_51;
extern void* __uxb_ffi_symptr_52;
extern void* __uxb_ffi_symptr_53;
extern void* __uxb_ffi_symptr_54;
extern void* __uxb_ffi_symptr_55;
extern void* __uxb_ffi_symptr_56;
extern void* __uxb_ffi_symptr_57;
extern void* __uxb_ffi_symptr_58;
extern void* __uxb_ffi_symptr_59;
extern void* __uxb_ffi_symptr_60;
extern void* __uxb_ffi_symptr_61;
extern void* __uxb_ffi_symptr_62;
extern void* __uxb_ffi_symptr_63;
extern void* __uxb_ffi_symptr_64;
extern void* __uxb_ffi_symptr_65;
extern void* __uxb_ffi_symptr_66;
extern void* __uxb_ffi_symptr_67;
extern void* __uxb_ffi_symptr_68;
extern void* __uxb_ffi_symptr_69;
extern void* __uxb_ffi_symptr_70;
extern void* __uxb_ffi_symptr_71;
extern void* __uxb_ffi_symptr_72;
extern void* __uxb_ffi_symptr_73;
extern void* __uxb_ffi_symptr_74;
extern void* __uxb_ffi_symptr_75;
extern void* __uxb_ffi_symptr_76;
extern void* __uxb_ffi_symptr_77;
extern void* __uxb_ffi_symptr_78;
extern void* __uxb_ffi_symptr_79;
extern void* __uxb_ffi_symptr_80;
extern void* __uxb_ffi_symptr_81;
extern void* __uxb_ffi_symptr_82;
extern void* __uxb_ffi_symptr_83;
extern void* __uxb_ffi_symptr_84;
extern void* __uxb_ffi_symptr_85;
extern void* __uxb_ffi_symptr_86;
extern void* __uxb_ffi_symptr_87;
extern void* __uxb_ffi_symptr_88;
extern void* __uxb_ffi_symptr_89;
extern void* __uxb_ffi_symptr_90;
extern void* __uxb_ffi_symptr_91;
extern void* __uxb_ffi_symptr_92;
extern void* __uxb_ffi_symptr_93;
extern void* __uxb_ffi_symptr_94;
extern void* __uxb_ffi_symptr_95;
extern void* __uxb_ffi_symptr_96;
extern void* __uxb_ffi_symptr_97;
extern void* __uxb_ffi_symptr_98;
extern void* __uxb_ffi_symptr_99;
extern void* __uxb_ffi_symptr_100;
extern void* __uxb_ffi_symptr_101;
extern void* __uxb_ffi_symptr_102;
extern void* __uxb_ffi_symptr_103;
extern void* __uxb_ffi_symptr_104;
extern void* __uxb_ffi_symptr_105;
extern void* __uxb_ffi_symptr_106;
extern void* __uxb_ffi_symptr_107;
extern void* __uxb_ffi_symptr_108;
extern void* __uxb_ffi_symptr_109;
extern void* __uxb_ffi_symptr_110;
extern void* __uxb_ffi_symptr_111;
extern void* __uxb_ffi_symptr_112;
extern void* __uxb_ffi_symptr_113;
extern void* __uxb_ffi_symptr_114;
extern void* __uxb_ffi_symptr_115;
extern void* __uxb_ffi_symptr_116;
extern void* __uxb_ffi_symptr_117;
extern void* __uxb_ffi_symptr_118;
extern void* __uxb_ffi_symptr_119;
extern void* __uxb_ffi_symptr_120;
extern void* __uxb_ffi_symptr_121;
extern void* __uxb_ffi_symptr_122;
extern void* __uxb_ffi_symptr_123;
extern void* __uxb_ffi_symptr_124;
extern void* __uxb_ffi_symptr_125;
extern void* __uxb_ffi_symptr_126;
extern void* __uxb_ffi_symptr_127;
extern void* __uxb_ffi_symptr_128;
extern void* __uxb_ffi_symptr_129;
extern void* __uxb_ffi_symptr_130;
extern void* __uxb_ffi_symptr_131;
extern void* __uxb_ffi_symptr_132;
extern void* __uxb_ffi_symptr_133;
extern void* __uxb_ffi_symptr_134;
extern void* __uxb_ffi_symptr_135;
extern void* __uxb_ffi_symptr_136;
extern void* __uxb_ffi_symptr_137;
extern void* __uxb_ffi_symptr_138;
extern void* __uxb_ffi_symptr_139;
extern void* __uxb_ffi_symptr_140;
extern void* __uxb_ffi_symptr_141;
extern void* __uxb_ffi_symptr_142;
extern void* __uxb_ffi_symptr_143;
extern void* __uxb_ffi_symptr_144;
extern void* __uxb_ffi_symptr_145;
extern void* __uxb_ffi_symptr_146;
extern void* __uxb_ffi_symptr_147;
extern void* __uxb_ffi_symptr_148;
extern void* __uxb_ffi_symptr_149;
extern void* __uxb_ffi_symptr_150;
extern void* __uxb_ffi_symptr_151;
extern void* __uxb_ffi_symptr_152;
extern void* __uxb_ffi_symptr_153;
extern void* __uxb_ffi_symptr_154;
extern void* __uxb_ffi_symptr_155;
extern void* __uxb_ffi_symptr_156;
extern void* __uxb_ffi_symptr_157;
extern void* __uxb_ffi_symptr_158;
extern void* __uxb_ffi_symptr_159;
extern void* __uxb_ffi_symptr_160;
extern void* __uxb_ffi_symptr_161;
extern void* __uxb_ffi_symptr_162;
extern void* __uxb_ffi_symptr_163;

static int uxb_is_absolute_dll_path(const char* path) {
    if (!path || !path[0]) return 0;
    if ((path[0] == '\\' && path[1] == '\\') || path[0] == '/') return 1;
    if (((path[0] >= 'A' && path[0] <= 'Z') || (path[0] >= 'a' && path[0] <= 'z')) && path[1] == ':') return 1;
    return 0;
}

static HMODULE uxb_load_library_for_program(const char* dll_name) {
    HMODULE h = LoadLibraryA(dll_name);
    if (h) return h;
    if (!dll_name || !dll_name[0] || uxb_is_absolute_dll_path(dll_name)) return NULL;
    char module_path[MAX_PATH];
    DWORD n = GetModuleFileNameA(NULL, module_path, MAX_PATH);
    if (n == 0 || n >= MAX_PATH) return NULL;
    char* tail = module_path + strlen(module_path);
    while (tail > module_path && tail[-1] != '\\' && tail[-1] != '/') --tail;
    *tail = '\0';
    size_t dir_len = strlen(module_path);
    size_t dll_len = strlen(dll_name);
    if (dir_len + 1 + dll_len + 1 > MAX_PATH) return NULL;
    char full_path[MAX_PATH];
    memcpy(full_path, module_path, dir_len);
    full_path[dir_len] = '\\';
    memcpy(full_path + dir_len + 1, dll_name, dll_len + 1);
    return LoadLibraryA(full_path);
}

static void uxb_resolve_fail(const char* op, const char* dll_name, const char* symbol_name) {
    fprintf(stderr, "uXBasic x64 FFI resolve failed: %s dll=%s symbol=%s\n", op ? op : "?", dll_name ? dll_name : "?", symbol_name ? symbol_name : "?");
    fflush(stderr);
    ExitProcess(127);
}

static void uxb_resolve_one(void** target, const char* dll_name, const char* symbol_name) {
    if (!target || *target) return;
    HMODULE h = uxb_load_library_for_program(dll_name);
    if (!h) uxb_resolve_fail("LoadLibraryA", dll_name, symbol_name);
    FARPROC proc = GetProcAddress(h, symbol_name);
    if (!proc) uxb_resolve_fail("GetProcAddress", dll_name, symbol_name);
    *target = (void*)proc;
}

__declspec(dllexport) void __uxb_ffi_resolve_all(void) {
    uxb_resolve_one(&__uxb_ffi_symptr_1, "uxcapi.dll", "uxcapi_version");
    uxb_resolve_one(&__uxb_ffi_symptr_2, "uxcapi.dll", "uxcapi_last_error");
    uxb_resolve_one(&__uxb_ffi_symptr_3, "uxcapi.dll", "uxcapi_shutdown");
    uxb_resolve_one(&__uxb_ffi_symptr_4, "uxcapi.dll", "uxcapi_symbol_address");
    uxb_resolve_one(&__uxb_ffi_symptr_5, "uxcapi.dll", "uxcapi_type_struct_new");
    uxb_resolve_one(&__uxb_ffi_symptr_6, "uxcapi.dll", "uxcapi_type_union_new");
    uxb_resolve_one(&__uxb_ffi_symptr_7, "uxcapi.dll", "uxcapi_type_add_field");
    uxb_resolve_one(&__uxb_ffi_symptr_8, "uxcapi.dll", "uxcapi_type_add_struct_field");
    uxb_resolve_one(&__uxb_ffi_symptr_9, "uxcapi.dll", "uxcapi_type_add_array_field");
    uxb_resolve_one(&__uxb_ffi_symptr_10, "uxcapi.dll", "uxcapi_type_add_struct_array_field");
    uxb_resolve_one(&__uxb_ffi_symptr_11, "uxcapi.dll", "uxcapi_type_set_expected_layout");
    uxb_resolve_one(&__uxb_ffi_symptr_12, "uxcapi.dll", "uxcapi_type_finalize");
    uxb_resolve_one(&__uxb_ffi_symptr_13, "uxcapi.dll", "uxcapi_type_kind");
    uxb_resolve_one(&__uxb_ffi_symptr_14, "uxcapi.dll", "uxcapi_type_size");
    uxb_resolve_one(&__uxb_ffi_symptr_15, "uxcapi.dll", "uxcapi_type_alignment");
    uxb_resolve_one(&__uxb_ffi_symptr_16, "uxcapi.dll", "uxcapi_type_free");
    uxb_resolve_one(&__uxb_ffi_symptr_17, "uxcapi.dll", "uxcapi_call_new");
    uxb_resolve_one(&__uxb_ffi_symptr_18, "uxcapi.dll", "uxcapi_call_free");
    uxb_resolve_one(&__uxb_ffi_symptr_19, "uxcapi.dll", "uxcapi_call_clear_arguments");
    uxb_resolve_one(&__uxb_ffi_symptr_20, "uxcapi.dll", "uxcapi_call_set_return_struct");
    uxb_resolve_one(&__uxb_ffi_symptr_21, "uxcapi.dll", "uxcapi_call_arg_i8");
    uxb_resolve_one(&__uxb_ffi_symptr_22, "uxcapi.dll", "uxcapi_call_arg_u8");
    uxb_resolve_one(&__uxb_ffi_symptr_23, "uxcapi.dll", "uxcapi_call_arg_i16");
    uxb_resolve_one(&__uxb_ffi_symptr_24, "uxcapi.dll", "uxcapi_call_arg_u16");
    uxb_resolve_one(&__uxb_ffi_symptr_25, "uxcapi.dll", "uxcapi_call_arg_i32");
    uxb_resolve_one(&__uxb_ffi_symptr_26, "uxcapi.dll", "uxcapi_call_arg_u32");
    uxb_resolve_one(&__uxb_ffi_symptr_27, "uxcapi.dll", "uxcapi_call_arg_i64");
    uxb_resolve_one(&__uxb_ffi_symptr_28, "uxcapi.dll", "uxcapi_call_arg_u64");
    uxb_resolve_one(&__uxb_ffi_symptr_29, "uxcapi.dll", "uxcapi_call_arg_f32");
    uxb_resolve_one(&__uxb_ffi_symptr_30, "uxcapi.dll", "uxcapi_call_arg_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_31, "uxcapi.dll", "uxcapi_call_arg_struct");
    uxb_resolve_one(&__uxb_ffi_symptr_32, "uxcapi.dll", "uxcapi_call_arg_ptr");
    uxb_resolve_one(&__uxb_ffi_symptr_33, "uxcapi.dll", "uxcapi_call_arg_string");
    uxb_resolve_one(&__uxb_ffi_symptr_34, "uxcapi.dll", "uxcapi_call_arg_wstring_utf8");
    uxb_resolve_one(&__uxb_ffi_symptr_35, "uxcapi.dll", "uxcapi_call_arg_long_double_from_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_36, "uxcapi.dll", "uxcapi_call_append_args");
    uxb_resolve_one(&__uxb_ffi_symptr_37, "uxcapi.dll", "uxcapi_call_invoke");
    uxb_resolve_one(&__uxb_ffi_symptr_38, "uxcapi.dll", "uxcapi_result_i32");
    uxb_resolve_one(&__uxb_ffi_symptr_39, "uxcapi.dll", "uxcapi_result_u32");
    uxb_resolve_one(&__uxb_ffi_symptr_40, "uxcapi.dll", "uxcapi_result_i64");
    uxb_resolve_one(&__uxb_ffi_symptr_41, "uxcapi.dll", "uxcapi_result_u64");
    uxb_resolve_one(&__uxb_ffi_symptr_42, "uxcapi.dll", "uxcapi_result_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_43, "uxcapi.dll", "uxcapi_result_ptr");
    uxb_resolve_one(&__uxb_ffi_symptr_44, "uxcapi.dll", "uxcapi_result_string");
    uxb_resolve_one(&__uxb_ffi_symptr_45, "uxcapi.dll", "uxcapi_result_struct_size");
    uxb_resolve_one(&__uxb_ffi_symptr_46, "uxcapi.dll", "uxcapi_result_struct_copy");
    uxb_resolve_one(&__uxb_ffi_symptr_47, "uxcapi.dll", "uxcapi_call_error");
    uxb_resolve_one(&__uxb_ffi_symptr_48, "uxcapi.dll", "uxcapi_args_new");
    uxb_resolve_one(&__uxb_ffi_symptr_49, "uxcapi.dll", "uxcapi_args_free");
    uxb_resolve_one(&__uxb_ffi_symptr_50, "uxcapi.dll", "uxcapi_args_clear");
    uxb_resolve_one(&__uxb_ffi_symptr_51, "uxcapi.dll", "uxcapi_args_add_i8");
    uxb_resolve_one(&__uxb_ffi_symptr_52, "uxcapi.dll", "uxcapi_args_add_u8");
    uxb_resolve_one(&__uxb_ffi_symptr_53, "uxcapi.dll", "uxcapi_args_add_i16");
    uxb_resolve_one(&__uxb_ffi_symptr_54, "uxcapi.dll", "uxcapi_args_add_u16");
    uxb_resolve_one(&__uxb_ffi_symptr_55, "uxcapi.dll", "uxcapi_args_add_i32");
    uxb_resolve_one(&__uxb_ffi_symptr_56, "uxcapi.dll", "uxcapi_args_add_u32");
    uxb_resolve_one(&__uxb_ffi_symptr_57, "uxcapi.dll", "uxcapi_args_add_i64");
    uxb_resolve_one(&__uxb_ffi_symptr_58, "uxcapi.dll", "uxcapi_args_add_u64");
    uxb_resolve_one(&__uxb_ffi_symptr_59, "uxcapi.dll", "uxcapi_args_add_f32");
    uxb_resolve_one(&__uxb_ffi_symptr_60, "uxcapi.dll", "uxcapi_args_add_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_61, "uxcapi.dll", "uxcapi_args_add_ptr");
    uxb_resolve_one(&__uxb_ffi_symptr_62, "uxcapi.dll", "uxcapi_args_add_string");
    uxb_resolve_one(&__uxb_ffi_symptr_63, "uxcapi.dll", "uxcapi_args_add_wstring_utf8");
    uxb_resolve_one(&__uxb_ffi_symptr_64, "uxcapi.dll", "uxcapi_args_add_long_double_from_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_65, "uxcapi.dll", "uxcapi_args_add_struct");
    uxb_resolve_one(&__uxb_ffi_symptr_66, "uxcapi.dll", "uxcapi_memory_alloc");
    uxb_resolve_one(&__uxb_ffi_symptr_67, "uxcapi.dll", "uxcapi_memory_calloc");
    uxb_resolve_one(&__uxb_ffi_symptr_68, "uxcapi.dll", "uxcapi_memory_realloc");
    uxb_resolve_one(&__uxb_ffi_symptr_69, "uxcapi.dll", "uxcapi_memory_free");
    uxb_resolve_one(&__uxb_ffi_symptr_70, "uxcapi.dll", "uxcapi_memory_zero");
    uxb_resolve_one(&__uxb_ffi_symptr_71, "uxcapi.dll", "uxcapi_memory_copy");
    uxb_resolve_one(&__uxb_ffi_symptr_72, "uxcapi.dll", "uxcapi_memory_write_i8");
    uxb_resolve_one(&__uxb_ffi_symptr_73, "uxcapi.dll", "uxcapi_memory_write_u8");
    uxb_resolve_one(&__uxb_ffi_symptr_74, "uxcapi.dll", "uxcapi_memory_write_i16");
    uxb_resolve_one(&__uxb_ffi_symptr_75, "uxcapi.dll", "uxcapi_memory_write_u16");
    uxb_resolve_one(&__uxb_ffi_symptr_76, "uxcapi.dll", "uxcapi_memory_write_i32");
    uxb_resolve_one(&__uxb_ffi_symptr_77, "uxcapi.dll", "uxcapi_memory_write_u32");
    uxb_resolve_one(&__uxb_ffi_symptr_78, "uxcapi.dll", "uxcapi_memory_write_i64");
    uxb_resolve_one(&__uxb_ffi_symptr_79, "uxcapi.dll", "uxcapi_memory_write_u64");
    uxb_resolve_one(&__uxb_ffi_symptr_80, "uxcapi.dll", "uxcapi_memory_write_f32");
    uxb_resolve_one(&__uxb_ffi_symptr_81, "uxcapi.dll", "uxcapi_memory_write_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_82, "uxcapi.dll", "uxcapi_memory_write_ptr");
    uxb_resolve_one(&__uxb_ffi_symptr_83, "uxcapi.dll", "uxcapi_memory_write_string");
    uxb_resolve_one(&__uxb_ffi_symptr_84, "uxcapi.dll", "uxcapi_memory_read_i8");
    uxb_resolve_one(&__uxb_ffi_symptr_85, "uxcapi.dll", "uxcapi_memory_read_u8");
    uxb_resolve_one(&__uxb_ffi_symptr_86, "uxcapi.dll", "uxcapi_memory_read_i16");
    uxb_resolve_one(&__uxb_ffi_symptr_87, "uxcapi.dll", "uxcapi_memory_read_u16");
    uxb_resolve_one(&__uxb_ffi_symptr_88, "uxcapi.dll", "uxcapi_memory_read_i32");
    uxb_resolve_one(&__uxb_ffi_symptr_89, "uxcapi.dll", "uxcapi_memory_read_u32");
    uxb_resolve_one(&__uxb_ffi_symptr_90, "uxcapi.dll", "uxcapi_memory_read_i64");
    uxb_resolve_one(&__uxb_ffi_symptr_91, "uxcapi.dll", "uxcapi_memory_read_u64");
    uxb_resolve_one(&__uxb_ffi_symptr_92, "uxcapi.dll", "uxcapi_memory_read_f32");
    uxb_resolve_one(&__uxb_ffi_symptr_93, "uxcapi.dll", "uxcapi_memory_read_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_94, "uxcapi.dll", "uxcapi_memory_read_ptr");
    uxb_resolve_one(&__uxb_ffi_symptr_95, "uxcapi.dll", "uxcapi_memory_read_string");
    uxb_resolve_one(&__uxb_ffi_symptr_96, "uxcapi.dll", "uxcapi_callback_new");
    uxb_resolve_one(&__uxb_ffi_symptr_97, "uxcapi.dll", "uxcapi_callback_add_arg");
    uxb_resolve_one(&__uxb_ffi_symptr_98, "uxcapi.dll", "uxcapi_callback_build");
    uxb_resolve_one(&__uxb_ffi_symptr_99, "uxcapi.dll", "uxcapi_callback_pointer");
    uxb_resolve_one(&__uxb_ffi_symptr_100, "uxcapi.dll", "uxcapi_callback_free");
    uxb_resolve_one(&__uxb_ffi_symptr_101, "uxcapi.dll", "uxcapi_callback_pending");
    uxb_resolve_one(&__uxb_ffi_symptr_102, "uxcapi.dll", "uxcapi_callback_next");
    uxb_resolve_one(&__uxb_ffi_symptr_103, "uxcapi.dll", "uxcapi_event_free");
    uxb_resolve_one(&__uxb_ffi_symptr_104, "uxcapi.dll", "uxcapi_event_arg_count");
    uxb_resolve_one(&__uxb_ffi_symptr_105, "uxcapi.dll", "uxcapi_event_arg_kind");
    uxb_resolve_one(&__uxb_ffi_symptr_106, "uxcapi.dll", "uxcapi_event_arg_u64");
    uxb_resolve_one(&__uxb_ffi_symptr_107, "uxcapi.dll", "uxcapi_event_arg_f64");
    uxb_resolve_one(&__uxb_ffi_symptr_108, "uxcapi.dll", "uxcapi_event_arg_string");
    uxb_resolve_one(&__uxb_ffi_symptr_109, "uxgsl.dll", "uxgsl_api_version");
    uxb_resolve_one(&__uxb_ffi_symptr_110, "uxgsl.dll", "uxgsl_available");
    uxb_resolve_one(&__uxb_ffi_symptr_111, "uxgsl.dll", "uxgsl_gsl_version");
    uxb_resolve_one(&__uxb_ffi_symptr_112, "uxgsl.dll", "uxgsl_self_test");
    uxb_resolve_one(&__uxb_ffi_symptr_113, "uxgsl.dll", "uxgsl_last_status");
    uxb_resolve_one(&__uxb_ffi_symptr_114, "uxgsl.dll", "uxgsl_last_gsl_status");
    uxb_resolve_one(&__uxb_ffi_symptr_115, "uxgsl.dll", "uxgsl_last_error");
    uxb_resolve_one(&__uxb_ffi_symptr_116, "uxgsl.dll", "uxgsl_status_text");
    uxb_resolve_one(&__uxb_ffi_symptr_117, "uxgsl.dll", "uxgsl_bessel_j0");
    uxb_resolve_one(&__uxb_ffi_symptr_118, "uxgsl.dll", "uxgsl_bessel_j1");
    uxb_resolve_one(&__uxb_ffi_symptr_119, "uxgsl.dll", "uxgsl_bessel_y0");
    uxb_resolve_one(&__uxb_ffi_symptr_120, "uxgsl.dll", "uxgsl_gamma");
    uxb_resolve_one(&__uxb_ffi_symptr_121, "uxgsl.dll", "uxgsl_lngamma");
    uxb_resolve_one(&__uxb_ffi_symptr_122, "uxgsl.dll", "uxgsl_erf");
    uxb_resolve_one(&__uxb_ffi_symptr_123, "uxgsl.dll", "uxgsl_gaussian_pdf");
    uxb_resolve_one(&__uxb_ffi_symptr_124, "uxgsl.dll", "uxgsl_rng_create");
    uxb_resolve_one(&__uxb_ffi_symptr_125, "uxgsl.dll", "uxgsl_rng_free");
    uxb_resolve_one(&__uxb_ffi_symptr_126, "uxgsl.dll", "uxgsl_rng_uniform");
    uxb_resolve_one(&__uxb_ffi_symptr_127, "uxgsl.dll", "uxgsl_rng_gaussian");
    uxb_resolve_one(&__uxb_ffi_symptr_128, "uxgsl.dll", "uxgsl_vector_create");
    uxb_resolve_one(&__uxb_ffi_symptr_129, "uxgsl.dll", "uxgsl_vector_free");
    uxb_resolve_one(&__uxb_ffi_symptr_130, "uxgsl.dll", "uxgsl_vector_size");
    uxb_resolve_one(&__uxb_ffi_symptr_131, "uxgsl.dll", "uxgsl_vector_set");
    uxb_resolve_one(&__uxb_ffi_symptr_132, "uxgsl.dll", "uxgsl_vector_get");
    uxb_resolve_one(&__uxb_ffi_symptr_133, "uxgsl.dll", "uxgsl_vector_mean");
    uxb_resolve_one(&__uxb_ffi_symptr_134, "uxgsl.dll", "uxgsl_vector_sd");
    uxb_resolve_one(&__uxb_ffi_symptr_135, "uxgsl.dll", "uxgsl_vector_variance");
    uxb_resolve_one(&__uxb_ffi_symptr_136, "uxgsl.dll", "uxgsl_matrix_create");
    uxb_resolve_one(&__uxb_ffi_symptr_137, "uxgsl.dll", "uxgsl_matrix_free");
    uxb_resolve_one(&__uxb_ffi_symptr_138, "uxgsl.dll", "uxgsl_matrix_rows");
    uxb_resolve_one(&__uxb_ffi_symptr_139, "uxgsl.dll", "uxgsl_matrix_columns");
    uxb_resolve_one(&__uxb_ffi_symptr_140, "uxgsl.dll", "uxgsl_matrix_set");
    uxb_resolve_one(&__uxb_ffi_symptr_141, "uxgsl.dll", "uxgsl_matrix_get");
    uxb_resolve_one(&__uxb_ffi_symptr_142, "uxgsl.dll", "uxgsl_matrix_set_zero");
    uxb_resolve_one(&__uxb_ffi_symptr_143, "uxgsl.dll", "uxgsl_matrix_set_identity");
    uxb_resolve_one(&__uxb_ffi_symptr_144, "uxgsl.dll", "uxgsl_matrix_multiply");
    uxb_resolve_one(&__uxb_ffi_symptr_145, "uxgsl.dll", "uxgsl_integration_workspace_create");
    uxb_resolve_one(&__uxb_ffi_symptr_146, "uxgsl.dll", "uxgsl_integration_workspace_free");
    uxb_resolve_one(&__uxb_ffi_symptr_147, "uxgsl.dll", "uxgsl_integrate_qag");
    uxb_resolve_one(&__uxb_ffi_symptr_148, "uxgsl.dll", "uxgsl_last_estimated_error");
    uxb_resolve_one(&__uxb_ffi_symptr_149, "uxgsl.dll", "uxgsl_root_bisection_create");
    uxb_resolve_one(&__uxb_ffi_symptr_150, "uxgsl.dll", "uxgsl_root_bisection_free");
    uxb_resolve_one(&__uxb_ffi_symptr_151, "uxgsl.dll", "uxgsl_root_bisection_set");
    uxb_resolve_one(&__uxb_ffi_symptr_152, "uxgsl.dll", "uxgsl_root_bisection_iterate");
    uxb_resolve_one(&__uxb_ffi_symptr_153, "uxgsl.dll", "uxgsl_root_bisection_root");
    uxb_resolve_one(&__uxb_ffi_symptr_154, "uxgsl.dll", "uxgsl_root_bisection_lower");
    uxb_resolve_one(&__uxb_ffi_symptr_155, "uxgsl.dll", "uxgsl_root_bisection_upper");
    uxb_resolve_one(&__uxb_ffi_symptr_156, "uxgsl.dll", "uxgsl_root_bisection_interval_converged");
    uxb_resolve_one(&__uxb_ffi_symptr_157, "uxgsl.dll", "uxgsl_complex_create");
    uxb_resolve_one(&__uxb_ffi_symptr_158, "uxgsl.dll", "uxgsl_complex_free");
    uxb_resolve_one(&__uxb_ffi_symptr_159, "uxgsl.dll", "uxgsl_complex_real");
    uxb_resolve_one(&__uxb_ffi_symptr_160, "uxgsl.dll", "uxgsl_complex_imaginary");
    uxb_resolve_one(&__uxb_ffi_symptr_161, "uxgsl.dll", "uxgsl_complex_abs");
    uxb_resolve_one(&__uxb_ffi_symptr_162, "uxgsl.dll", "uxgsl_complex_add");
    uxb_resolve_one(&__uxb_ffi_symptr_163, "uxgsl.dll", "uxgsl_complex_multiply");
}
