#ifndef UXB_SEMANTIC_JSON_REPORT_FBS
#define UXB_SEMANTIC_JSON_REPORT_FBS
Function SemStep3JsonEscape(ByRef s As String) As String
    Dim outText As String
    outText = ""
    Dim i As Integer
    For i = 1 To Len(s)
        Dim ch As String
        ch = Mid(s, i, 1)
        Select Case ch
        Case "\"
            outText &= "\\"
        Case Chr(34)
            outText &= "\" & Chr(34)
        Case Chr(13)
            outText &= "\r"
        Case Chr(10)
            outText &= "\n"
        Case Chr(9)
            outText &= "\t"
        Case Else
            outText &= ch
        End Select
    Next i
    Return outText
End Function
Function SemStep3JsonSummary(ByRef statusText As String, ByRef messageText As String) As String
    Return "{" & Chr(34) & "semantic_status" & Chr(34) & ":" & Chr(34) & SemStep3JsonEscape(statusText) & Chr(34) & "," & Chr(34) & "message" & Chr(34) & ":" & Chr(34) & SemStep3JsonEscape(messageText) & Chr(34) & "}"
End Function
#endif
