INTERFACE IAnimal
METHOD Speak()
END INTERFACE

TYPE Pair
lo AS I16
hi AS I16
END TYPE

TYPE Packet
tag AS I8
pairs(0 TO 1) AS Pair
word AS I32
END TYPE

CLASS Animal
PUBLIC
name AS I32
VIRTUAL METHOD Speak() AS I32
END CLASS

CLASS Dog EXTENDS Animal IMPLEMENTS IAnimal
PUBLIC
breed AS I32
OVERRIDE METHOD Speak() AS I32
END CLASS

FUNCTION ANIMAL_SPEAK(self AS I32) AS I32
ANIMAL_SPEAK = 11
END FUNCTION

FUNCTION DOG_SPEAK(self AS I32) AS I32
DOG_SPEAK = 22
END FUNCTION

FUNCTION AUTH_PROBE() AS I32
DIM d AS Dog
AUTH_PROBE = d.Speak()
END FUNCTION

DIM l AS LIST

MAIN
DIM m AS DICT
DIM n AS SET
DIM p AS Packet

PRINT "list="; l
PRINT "dict="; m
PRINT "set="; n
PRINT "packet-word-ofs="; OFFSETOF(Packet, "word")
PRINT "speak="; AUTH_PROBE()
END MAIN
