INTERFACE IFoo
METHOD Speak()
END INTERFACE

CLASS Base
PUBLIC
VIRTUAL METHOD Speak() AS I32
END CLASS

CLASS Dog EXTENDS Base IMPLEMENTS IFoo
PUBLIC
tag AS I32
OVERRIDE METHOD Speak() AS I32
END CLASS

FUNCTION BASE_SPEAK(self AS I32) AS I32
BASE_SPEAK = 11
END FUNCTION

FUNCTION DOG_SPEAK(self AS I32) AS I32
DOG_SPEAK = 42
END FUNCTION

DIM d AS Dog
PRINT d.Speak()
