TYPE V2
    X AS I32
    Y AS I32
END TYPE

MAIN
DIM p AS V2

POKED VARPTR(p) + OFFSETOF(V2, "X"), 10
POKED VARPTR(p) + OFFSETOF(V2, "Y"), PEEKD(VARPTR(p) + OFFSETOF(V2, "X")) + 5

PRINT OFFSETOF(V2, "X")
PRINT OFFSETOF(V2, "Y")
PRINT PEEKD(VARPTR(p) + OFFSETOF(V2, "X"))
PRINT PEEKD(VARPTR(p) + OFFSETOF(V2, "Y"))
END MAIN