#ifndef UXB_TYPE_KINDS_FBS
#define UXB_TYPE_KINDS_FBS
Const TYPE_VOID As String = "TYPE_VOID"
Const TYPE_BOOL As String = "TYPE_BOOL"
Const TYPE_I8 As String = "TYPE_I8"
Const TYPE_U8 As String = "TYPE_U8"
Const TYPE_I16 As String = "TYPE_I16"
Const TYPE_U16 As String = "TYPE_U16"
Const TYPE_I32 As String = "TYPE_I32"
Const TYPE_U32 As String = "TYPE_U32"
Const TYPE_I64 As String = "TYPE_I64"
Const TYPE_U64 As String = "TYPE_U64"
Const TYPE_F32 As String = "TYPE_F32"
Const TYPE_F64 As String = "TYPE_F64"
Const TYPE_F80 As String = "TYPE_F80"
Const TYPE_F128 As String = "TYPE_F128"
Const TYPE_BIGINT As String = "TYPE_BIGINT"
Const TYPE_BIGFLOAT As String = "TYPE_BIGFLOAT"
Const TYPE_BIGD As String = "TYPE_BIGD"
Const TYPE_BALL As String = "TYPE_BALL"
Const TYPE_STRING As String = "TYPE_STRING"
Const TYPE_WSTRING As String = "TYPE_WSTRING"
Const TYPE_PTR As String = "TYPE_PTR"
Const TYPE_STRPTR As String = "TYPE_STRPTR"
Const TYPE_WSTRPTR As String = "TYPE_WSTRPTR"
Const TYPE_ARRAY As String = "TYPE_ARRAY"
Const TYPE_OBJECT As String = "TYPE_OBJECT"
Const TYPE_VARIANT As String = "TYPE_VARIANT"
Const TYPE_ANY As String = "TYPE_ANY"
Const TYPE_TYPEDEF As String = "TYPE_TYPEDEF"
Const TYPE_CLASS As String = "TYPE_CLASS"
Const TYPE_INTERFACE As String = "TYPE_INTERFACE"
Const TYPE_FUNCTION_PTR As String = "TYPE_FUNCTION_PTR"
Const TYPE_DLL_HANDLE As String = "TYPE_DLL_HANDLE"
Const TYPE_FILE_HANDLE As String = "TYPE_FILE_HANDLE"
Const TYPE_JS_OBJECT As String = "TYPE_JS_OBJECT"
Const TYPE_WASM_EXTERNREF As String = "TYPE_WASM_EXTERNREF"
Const TYPE_TASK As String = "TYPE_TASK"
Const TYPE_TASKGROUP As String = "TYPE_TASKGROUP"
Const TYPE_UNKNOWN As String = "TYPE_UNKNOWN"
Const TYPE_ERROR As String = "TYPE_ERROR"
#endif
