' uxraylib 3D geometry without a window (S-052, raylib Models/3D dilimi 2): collision, rays, Camera3D handles, world<->screen.
' Builds on uxraylib_math_core.bas: a Ray is two vector SLOTS (position slot, direction slot), a BoundingBox two slots (min, max),
' a triangle/quad corner one slot each -- fill slots with VectorSlotSet. Ray-collision results are read with RayHit / RayDistance /
' RayPoint(component) / RayNormal(component). A Camera3D is a HANDLE (CameraCreate ... CameraRelease); camera projection
' 0 = perspective, 1 = orthographic. Vector results (WorldToScreen, ScreenToWorldRay) are read from the result registers
' (ResX/ResY/ResGet). Generated by tools/library_tools/gen_uxraylib_wrappers.ps1 from uxraylib_3d_cpu.inc.
NAMESPACE uxraylib
FUNCTION CheckCollisionSpheres(c1x AS F64, c1y AS F64, c1z AS F64, r1 AS F64, c2x AS F64, c2y AS F64, c2z AS F64, r2 AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_check_collision_spheres", I32, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", c1x, c1y, c1z, r1, c2x, c2y, c2z, r2)
END FUNCTION
FUNCTION CheckCollisionBoxesSlots(min1 AS I32, max1 AS I32, min2 AS I32, max2 AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_check_collision_boxes_slots", I32, CDECL, "I32,I32,I32,I32", min1, max1, min2, max2)
END FUNCTION
FUNCTION CheckCollisionBoxSphereSlots(minSlot AS I32, maxSlot AS I32, cx AS F64, cy AS F64, cz AS F64, radius AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_check_collision_box_sphere_slots", I32, CDECL, "I32,I32,F64,F64,F64,F64", minSlot, maxSlot, cx, cy, cz, radius)
END FUNCTION
FUNCTION RayCollisionSphereSlots(posSlot AS I32, dirSlot AS I32, cx AS F64, cy AS F64, cz AS F64, radius AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_collision_sphere_slots", I32, CDECL, "I32,I32,F64,F64,F64,F64", posSlot, dirSlot, cx, cy, cz, radius)
END FUNCTION
FUNCTION RayCollisionBoxSlots(posSlot AS I32, dirSlot AS I32, minSlot AS I32, maxSlot AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_collision_box_slots", I32, CDECL, "I32,I32,I32,I32", posSlot, dirSlot, minSlot, maxSlot)
END FUNCTION
FUNCTION RayCollisionTriangleSlots(posSlot AS I32, dirSlot AS I32, p1 AS I32, p2 AS I32, p3 AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_collision_triangle_slots", I32, CDECL, "I32,I32,I32,I32,I32", posSlot, dirSlot, p1, p2, p3)
END FUNCTION
FUNCTION RayCollisionQuadSlots(posSlot AS I32, dirSlot AS I32, p1 AS I32, p2 AS I32, p3 AS I32, p4 AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_collision_quad_slots", I32, CDECL, "I32,I32,I32,I32,I32,I32", posSlot, dirSlot, p1, p2, p3, p4)
END FUNCTION
FUNCTION RayHit() AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_hit", I32, CDECL)
END FUNCTION
FUNCTION RayDistance() AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_distance", F64, CDECL)
END FUNCTION
' component 0=x 1=y 2=z
FUNCTION RayPoint(component AS I32) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_point", F64, CDECL, "I32", component)
END FUNCTION
FUNCTION RayNormal(component AS I32) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_ray_normal", F64, CDECL, "I32", component)
END FUNCTION
' projection: 0 = CAMERA_PERSPECTIVE, 1 = CAMERA_ORTHOGRAPHIC (raylib's own values are 0 and 1).
FUNCTION CameraCreate(posSlot AS I32, targetSlot AS I32, upSlot AS I32, fovy AS F64, projection AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_camera_create", I32, CDECL, "I32,I32,I32,F64,I32", posSlot, targetSlot, upSlot, fovy, projection)
END FUNCTION
SUB CameraRelease(handle AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_camera_release", VOID, CDECL, "I32", handle)
END SUB
FUNCTION CameraValid(handle AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_camera_valid", I32, CDECL, "I32", handle)
END FUNCTION
' part: 0 position, 1 target, 2 up (component 0..2 = x y z); part 3 = fovy (component ignored); part 4 = projection
FUNCTION CameraGet(handle AS I32, part AS I32, component AS I32) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_camera_get", F64, CDECL, "I32,I32,I32", handle, part, component)
END FUNCTION
SUB CameraSet(handle AS I32, part AS I32, x AS F64, y AS F64, z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_camera_set", VOID, CDECL, "I32,I32,F64,F64,F64", handle, part, x, y, z)
END SUB
' UpdateCameraPro: movement (forward, right, up), rotation (yaw, pitch, roll in degrees), zoom (distance change).
SUB CameraUpdatePro(handle AS I32, moveForward AS F64, moveRight AS F64, moveUp AS F64, yaw AS F64, pitch AS F64, roll AS F64, zoom AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_camera_update_pro", VOID, CDECL, "I32,F64,F64,F64,F64,F64,F64,F64", handle, moveForward, moveRight, moveUp, yaw, pitch, roll, zoom)
END SUB
' view matrix (raylib GetCameraMatrix); returns a matrix handle
FUNCTION CameraMatrix(handle AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_camera_matrix", I32, CDECL, "I32", handle)
END FUNCTION
' GetWorldToScreenEx: register 0 = (x, y) in pixels for a window of width x height
SUB WorldToScreen(handle AS I32, px AS F64, py AS F64, pz AS F64, width AS I32, height AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_world_to_screen", VOID, CDECL, "I32,F64,F64,F64,I32,I32", handle, px, py, pz, width, height)
END SUB
' GetScreenToWorldRayEx: register 0 = ray origin, register 1 = ray direction
SUB ScreenToWorldRay(handle AS I32, sx AS F64, sy AS F64, width AS I32, height AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_screen_to_world_ray", VOID, CDECL, "I32,F64,F64,I32,I32", handle, sx, sy, width, height)
END SUB

END NAMESPACE
