' Generated by tools/library_tools/gen_uxraylib_math.py from raymath.h -- do not edit.
' raylib raymath (CPU only, no window needed). Vector/Quaternion results are read with ResX/ResY/ResZ/ResW;
' Matrix values are HANDLES (I32, 0 = invalid): every Matrix-producing function returns a new handle -> MatrixRelease.
NAMESPACE uxraylib

FUNCTION Clamp(value AS F64, minValue AS F64, maxValue AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_clamp", F64, CDECL, "F64,F64,F64", value, minValue, maxValue)
END FUNCTION
FUNCTION Lerp(begin AS F64, finish AS F64, amount AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_lerp", F64, CDECL, "F64,F64,F64", begin, finish, amount)
END FUNCTION
FUNCTION Normalize(value AS F64, begin AS F64, finish AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_normalize", F64, CDECL, "F64,F64,F64", value, begin, finish)
END FUNCTION
FUNCTION Remap(value AS F64, inputStart AS F64, inputEnd AS F64, outputStart AS F64, outputEnd AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_remap", F64, CDECL, "F64,F64,F64,F64,F64", value, inputStart, inputEnd, outputStart, outputEnd)
END FUNCTION
FUNCTION Wrap(value AS F64, minValue AS F64, maxValue AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_wrap", F64, CDECL, "F64,F64,F64", value, minValue, maxValue)
END FUNCTION
FUNCTION FloatEquals(x AS F64, y AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_float_equals", I32, CDECL, "F64,F64", x, y)
END FUNCTION
SUB Vector2Zero()
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_zero", VOID, CDECL)
END SUB
SUB Vector2One()
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_one", VOID, CDECL)
END SUB
SUB Vector2Add(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_add", VOID, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END SUB
SUB Vector2AddValue(vx AS F64, vy AS F64, addend AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_add_value", VOID, CDECL, "F64,F64,F64", vx, vy, addend)
END SUB
SUB Vector2Subtract(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_subtract", VOID, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END SUB
SUB Vector2SubtractValue(vx AS F64, vy AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_subtract_value", VOID, CDECL, "F64,F64,F64", vx, vy, amount)
END SUB
FUNCTION Vector2Length(vx AS F64, vy AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_length", F64, CDECL, "F64,F64", vx, vy)
END FUNCTION
FUNCTION Vector2LengthSqr(vx AS F64, vy AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_length_sqr", F64, CDECL, "F64,F64", vx, vy)
END FUNCTION
FUNCTION Vector2DotProduct(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_dot_product", F64, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END FUNCTION
FUNCTION Vector2Distance(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_distance", F64, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END FUNCTION
FUNCTION Vector2DistanceSqr(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_distance_sqr", F64, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END FUNCTION
FUNCTION Vector2Angle(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_angle", F64, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END FUNCTION
FUNCTION Vector2LineAngle(beginx AS F64, beginy AS F64, finishx AS F64, finishy AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_line_angle", F64, CDECL, "F64,F64,F64,F64", beginx, beginy, finishx, finishy)
END FUNCTION
SUB Vector2Scale(vx AS F64, vy AS F64, scale AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_scale", VOID, CDECL, "F64,F64,F64", vx, vy, scale)
END SUB
SUB Vector2Multiply(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_multiply", VOID, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END SUB
SUB Vector2Negate(vx AS F64, vy AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_negate", VOID, CDECL, "F64,F64", vx, vy)
END SUB
SUB Vector2Divide(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_divide", VOID, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END SUB
SUB Vector2Normalize(vx AS F64, vy AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_normalize", VOID, CDECL, "F64,F64", vx, vy)
END SUB
SUB Vector2Transform(vx AS F64, vy AS F64, matrix AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_transform", VOID, CDECL, "F64,F64,I32", vx, vy, matrix)
END SUB
SUB Vector2Lerp(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_lerp", VOID, CDECL, "F64,F64,F64,F64,F64", v1x, v1y, v2x, v2y, amount)
END SUB
SUB Vector2Reflect(vx AS F64, vy AS F64, normalx AS F64, normaly AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_reflect", VOID, CDECL, "F64,F64,F64,F64", vx, vy, normalx, normaly)
END SUB
SUB Vector2Min(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_min", VOID, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END SUB
SUB Vector2Max(v1x AS F64, v1y AS F64, v2x AS F64, v2y AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_max", VOID, CDECL, "F64,F64,F64,F64", v1x, v1y, v2x, v2y)
END SUB
SUB Vector2Rotate(vx AS F64, vy AS F64, angle AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_rotate", VOID, CDECL, "F64,F64,F64", vx, vy, angle)
END SUB
SUB Vector2MoveTowards(vx AS F64, vy AS F64, targetx AS F64, targety AS F64, maxDistance AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_move_towards", VOID, CDECL, "F64,F64,F64,F64,F64", vx, vy, targetx, targety, maxDistance)
END SUB
SUB Vector2Invert(vx AS F64, vy AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_invert", VOID, CDECL, "F64,F64", vx, vy)
END SUB
SUB Vector2Clamp(vx AS F64, vy AS F64, minValuex AS F64, minValuey AS F64, maxValuex AS F64, maxValuey AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_clamp", VOID, CDECL, "F64,F64,F64,F64,F64,F64", vx, vy, minValuex, minValuey, maxValuex, maxValuey)
END SUB
SUB Vector2ClampValue(vx AS F64, vy AS F64, minValue AS F64, maxValue AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_clamp_value", VOID, CDECL, "F64,F64,F64,F64", vx, vy, minValue, maxValue)
END SUB
FUNCTION Vector2Equals(px AS F64, py AS F64, qx AS F64, qy AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector2_equals", I32, CDECL, "F64,F64,F64,F64", px, py, qx, qy)
END FUNCTION
SUB Vector2Refract(vx AS F64, vy AS F64, nx AS F64, ny AS F64, r AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector2_refract", VOID, CDECL, "F64,F64,F64,F64,F64", vx, vy, nx, ny, r)
END SUB
SUB Vector3Zero()
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_zero", VOID, CDECL)
END SUB
SUB Vector3One()
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_one", VOID, CDECL)
END SUB
SUB Vector3Add(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_add", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3AddValue(vx AS F64, vy AS F64, vz AS F64, addend AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_add_value", VOID, CDECL, "F64,F64,F64,F64", vx, vy, vz, addend)
END SUB
SUB Vector3Subtract(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_subtract", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3SubtractValue(vx AS F64, vy AS F64, vz AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_subtract_value", VOID, CDECL, "F64,F64,F64,F64", vx, vy, vz, amount)
END SUB
SUB Vector3Scale(vx AS F64, vy AS F64, vz AS F64, scalar AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_scale", VOID, CDECL, "F64,F64,F64,F64", vx, vy, vz, scalar)
END SUB
SUB Vector3Multiply(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_multiply", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3CrossProduct(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_cross_product", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3Perpendicular(vx AS F64, vy AS F64, vz AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_perpendicular", VOID, CDECL, "F64,F64,F64", vx, vy, vz)
END SUB
FUNCTION Vector3Length(vx AS F64, vy AS F64, vz AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector3_length", F64, CDECL, "F64,F64,F64", vx, vy, vz)
END FUNCTION
FUNCTION Vector3LengthSqr(vx AS F64, vy AS F64, vz AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector3_length_sqr", F64, CDECL, "F64,F64,F64", vx, vy, vz)
END FUNCTION
FUNCTION Vector3DotProduct(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector3_dot_product", F64, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END FUNCTION
FUNCTION Vector3Distance(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector3_distance", F64, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END FUNCTION
FUNCTION Vector3DistanceSqr(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector3_distance_sqr", F64, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END FUNCTION
FUNCTION Vector3Angle(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector3_angle", F64, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END FUNCTION
SUB Vector3Negate(vx AS F64, vy AS F64, vz AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_negate", VOID, CDECL, "F64,F64,F64", vx, vy, vz)
END SUB
SUB Vector3Divide(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_divide", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3Normalize(vx AS F64, vy AS F64, vz AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_normalize", VOID, CDECL, "F64,F64,F64", vx, vy, vz)
END SUB
SUB Vector3Project(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_project", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3Reject(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_reject", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3Transform(vx AS F64, vy AS F64, vz AS F64, matrix AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_transform", VOID, CDECL, "F64,F64,F64,I32", vx, vy, vz, matrix)
END SUB
SUB Vector3RotateByQuaternion(vx AS F64, vy AS F64, vz AS F64, qx AS F64, qy AS F64, qz AS F64, qw AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_rotate_by_quaternion", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64", vx, vy, vz, qx, qy, qz, qw)
END SUB
SUB Vector3RotateByAxisAngle(vx AS F64, vy AS F64, vz AS F64, axisx AS F64, axisy AS F64, axisz AS F64, angle AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_rotate_by_axis_angle", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64", vx, vy, vz, axisx, axisy, axisz, angle)
END SUB
SUB Vector3MoveTowards(vx AS F64, vy AS F64, vz AS F64, targetx AS F64, targety AS F64, targetz AS F64, maxDistance AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_move_towards", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64", vx, vy, vz, targetx, targety, targetz, maxDistance)
END SUB
SUB Vector3Lerp(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_lerp", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z, amount)
END SUB
SUB Vector3Reflect(vx AS F64, vy AS F64, vz AS F64, normalx AS F64, normaly AS F64, normalz AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_reflect", VOID, CDECL, "F64,F64,F64,F64,F64,F64", vx, vy, vz, normalx, normaly, normalz)
END SUB
SUB Vector3Min(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_min", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3Max(v1x AS F64, v1y AS F64, v1z AS F64, v2x AS F64, v2y AS F64, v2z AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_max", VOID, CDECL, "F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v2x, v2y, v2z)
END SUB
SUB Vector3Unproject(sourcex AS F64, sourcey AS F64, sourcez AS F64, projection AS I32, view AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_unproject", VOID, CDECL, "F64,F64,F64,I32,I32", sourcex, sourcey, sourcez, projection, view)
END SUB
SUB Vector3Invert(vx AS F64, vy AS F64, vz AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_invert", VOID, CDECL, "F64,F64,F64", vx, vy, vz)
END SUB
SUB Vector3Clamp(vx AS F64, vy AS F64, vz AS F64, minValuex AS F64, minValuey AS F64, minValuez AS F64, maxValuex AS F64, maxValuey AS F64, maxValuez AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_clamp", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64,F64", vx, vy, vz, minValuex, minValuey, minValuez, maxValuex, maxValuey, maxValuez)
END SUB
SUB Vector3ClampValue(vx AS F64, vy AS F64, vz AS F64, minValue AS F64, maxValue AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_clamp_value", VOID, CDECL, "F64,F64,F64,F64,F64", vx, vy, vz, minValue, maxValue)
END SUB
FUNCTION Vector3Equals(px AS F64, py AS F64, pz AS F64, qx AS F64, qy AS F64, qz AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector3_equals", I32, CDECL, "F64,F64,F64,F64,F64,F64", px, py, pz, qx, qy, qz)
END FUNCTION
SUB Vector3Refract(vx AS F64, vy AS F64, vz AS F64, nx AS F64, ny AS F64, nz AS F64, r AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector3_refract", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64", vx, vy, vz, nx, ny, nz, r)
END SUB
SUB Vector4Zero()
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_zero", VOID, CDECL)
END SUB
SUB Vector4One()
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_one", VOID, CDECL)
END SUB
SUB Vector4Add(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_add", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END SUB
SUB Vector4AddValue(vx AS F64, vy AS F64, vz AS F64, vw AS F64, addend AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_add_value", VOID, CDECL, "F64,F64,F64,F64,F64", vx, vy, vz, vw, addend)
END SUB
SUB Vector4Subtract(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_subtract", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END SUB
SUB Vector4SubtractValue(vx AS F64, vy AS F64, vz AS F64, vw AS F64, addend AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_subtract_value", VOID, CDECL, "F64,F64,F64,F64,F64", vx, vy, vz, vw, addend)
END SUB
FUNCTION Vector4Length(vx AS F64, vy AS F64, vz AS F64, vw AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector4_length", F64, CDECL, "F64,F64,F64,F64", vx, vy, vz, vw)
END FUNCTION
FUNCTION Vector4LengthSqr(vx AS F64, vy AS F64, vz AS F64, vw AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector4_length_sqr", F64, CDECL, "F64,F64,F64,F64", vx, vy, vz, vw)
END FUNCTION
FUNCTION Vector4DotProduct(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector4_dot_product", F64, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END FUNCTION
FUNCTION Vector4Distance(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector4_distance", F64, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END FUNCTION
FUNCTION Vector4DistanceSqr(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector4_distance_sqr", F64, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END FUNCTION
SUB Vector4Scale(vx AS F64, vy AS F64, vz AS F64, vw AS F64, scale AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_scale", VOID, CDECL, "F64,F64,F64,F64,F64", vx, vy, vz, vw, scale)
END SUB
SUB Vector4Multiply(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_multiply", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END SUB
SUB Vector4Negate(vx AS F64, vy AS F64, vz AS F64, vw AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_negate", VOID, CDECL, "F64,F64,F64,F64", vx, vy, vz, vw)
END SUB
SUB Vector4Divide(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_divide", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END SUB
SUB Vector4Normalize(vx AS F64, vy AS F64, vz AS F64, vw AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_normalize", VOID, CDECL, "F64,F64,F64,F64", vx, vy, vz, vw)
END SUB
SUB Vector4Min(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_min", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END SUB
SUB Vector4Max(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_max", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w)
END SUB
SUB Vector4Lerp(v1x AS F64, v1y AS F64, v1z AS F64, v1w AS F64, v2x AS F64, v2y AS F64, v2z AS F64, v2w AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_lerp", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64,F64", v1x, v1y, v1z, v1w, v2x, v2y, v2z, v2w, amount)
END SUB
SUB Vector4MoveTowards(vx AS F64, vy AS F64, vz AS F64, vw AS F64, targetx AS F64, targety AS F64, targetz AS F64, targetw AS F64, maxDistance AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_move_towards", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64,F64", vx, vy, vz, vw, targetx, targety, targetz, targetw, maxDistance)
END SUB
SUB Vector4Invert(vx AS F64, vy AS F64, vz AS F64, vw AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_vector4_invert", VOID, CDECL, "F64,F64,F64,F64", vx, vy, vz, vw)
END SUB
FUNCTION Vector4Equals(px AS F64, py AS F64, pz AS F64, pw AS F64, qx AS F64, qy AS F64, qz AS F64, qw AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_vector4_equals", I32, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", px, py, pz, pw, qx, qy, qz, qw)
END FUNCTION
FUNCTION MatrixDeterminant(matrix AS I32) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_determinant", F64, CDECL, "I32", matrix)
END FUNCTION
FUNCTION MatrixTrace(matrix AS I32) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_trace", F64, CDECL, "I32", matrix)
END FUNCTION
FUNCTION MatrixTranspose(matrix AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_transpose", I32, CDECL, "I32", matrix)
END FUNCTION
FUNCTION MatrixInvert(matrix AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_invert", I32, CDECL, "I32", matrix)
END FUNCTION
FUNCTION MatrixIdentity() AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_identity", I32, CDECL)
END FUNCTION
FUNCTION MatrixAdd(leftEdge AS I32, rightEdge AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_add", I32, CDECL, "I32,I32", leftEdge, rightEdge)
END FUNCTION
FUNCTION MatrixSubtract(leftEdge AS I32, rightEdge AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_subtract", I32, CDECL, "I32,I32", leftEdge, rightEdge)
END FUNCTION
FUNCTION MatrixMultiply(leftEdge AS I32, rightEdge AS I32) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_multiply", I32, CDECL, "I32,I32", leftEdge, rightEdge)
END FUNCTION
FUNCTION MatrixTranslate(x AS F64, y AS F64, z AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_translate", I32, CDECL, "F64,F64,F64", x, y, z)
END FUNCTION
FUNCTION MatrixRotate(axisx AS F64, axisy AS F64, axisz AS F64, angle AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_rotate", I32, CDECL, "F64,F64,F64,F64", axisx, axisy, axisz, angle)
END FUNCTION
FUNCTION MatrixRotateX(angle AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_rotate_x", I32, CDECL, "F64", angle)
END FUNCTION
FUNCTION MatrixRotateY(angle AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_rotate_y", I32, CDECL, "F64", angle)
END FUNCTION
FUNCTION MatrixRotateZ(angle AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_rotate_z", I32, CDECL, "F64", angle)
END FUNCTION
FUNCTION MatrixRotateXYZ(anglex AS F64, angley AS F64, anglez AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_rotate_xyz", I32, CDECL, "F64,F64,F64", anglex, angley, anglez)
END FUNCTION
FUNCTION MatrixRotateZYX(anglex AS F64, angley AS F64, anglez AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_rotate_zyx", I32, CDECL, "F64,F64,F64", anglex, angley, anglez)
END FUNCTION
FUNCTION MatrixScale(x AS F64, y AS F64, z AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_scale", I32, CDECL, "F64,F64,F64", x, y, z)
END FUNCTION
FUNCTION MatrixFrustum(leftEdge AS F64, rightEdge AS F64, bottomEdge AS F64, topEdge AS F64, nearPlane AS F64, farPlane AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_frustum", I32, CDECL, "F64,F64,F64,F64,F64,F64", leftEdge, rightEdge, bottomEdge, topEdge, nearPlane, farPlane)
END FUNCTION
FUNCTION MatrixPerspective(fovY AS F64, aspect AS F64, nearPlane AS F64, farPlane AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_perspective", I32, CDECL, "F64,F64,F64,F64", fovY, aspect, nearPlane, farPlane)
END FUNCTION
FUNCTION MatrixOrtho(leftEdge AS F64, rightEdge AS F64, bottomEdge AS F64, topEdge AS F64, nearPlane AS F64, farPlane AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_ortho", I32, CDECL, "F64,F64,F64,F64,F64,F64", leftEdge, rightEdge, bottomEdge, topEdge, nearPlane, farPlane)
END FUNCTION
FUNCTION MatrixLookAt(eyex AS F64, eyey AS F64, eyez AS F64, targetx AS F64, targety AS F64, targetz AS F64, upx AS F64, upy AS F64, upz AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_matrix_look_at", I32, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64,F64", eyex, eyey, eyez, targetx, targety, targetz, upx, upy, upz)
END FUNCTION
SUB QuaternionAdd(q1x AS F64, q1y AS F64, q1z AS F64, q1w AS F64, q2x AS F64, q2y AS F64, q2z AS F64, q2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_add", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", q1x, q1y, q1z, q1w, q2x, q2y, q2z, q2w)
END SUB
SUB QuaternionAddValue(qx AS F64, qy AS F64, qz AS F64, qw AS F64, addend AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_add_value", VOID, CDECL, "F64,F64,F64,F64,F64", qx, qy, qz, qw, addend)
END SUB
SUB QuaternionSubtract(q1x AS F64, q1y AS F64, q1z AS F64, q1w AS F64, q2x AS F64, q2y AS F64, q2z AS F64, q2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_subtract", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", q1x, q1y, q1z, q1w, q2x, q2y, q2z, q2w)
END SUB
SUB QuaternionSubtractValue(qx AS F64, qy AS F64, qz AS F64, qw AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_subtract_value", VOID, CDECL, "F64,F64,F64,F64,F64", qx, qy, qz, qw, amount)
END SUB
SUB QuaternionIdentity()
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_identity", VOID, CDECL)
END SUB
FUNCTION QuaternionLength(qx AS F64, qy AS F64, qz AS F64, qw AS F64) AS F64
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_length", F64, CDECL, "F64,F64,F64,F64", qx, qy, qz, qw)
END FUNCTION
SUB QuaternionNormalize(qx AS F64, qy AS F64, qz AS F64, qw AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_normalize", VOID, CDECL, "F64,F64,F64,F64", qx, qy, qz, qw)
END SUB
SUB QuaternionInvert(qx AS F64, qy AS F64, qz AS F64, qw AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_invert", VOID, CDECL, "F64,F64,F64,F64", qx, qy, qz, qw)
END SUB
SUB QuaternionMultiply(q1x AS F64, q1y AS F64, q1z AS F64, q1w AS F64, q2x AS F64, q2y AS F64, q2z AS F64, q2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_multiply", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", q1x, q1y, q1z, q1w, q2x, q2y, q2z, q2w)
END SUB
SUB QuaternionScale(qx AS F64, qy AS F64, qz AS F64, qw AS F64, factor AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_scale", VOID, CDECL, "F64,F64,F64,F64,F64", qx, qy, qz, qw, factor)
END SUB
SUB QuaternionDivide(q1x AS F64, q1y AS F64, q1z AS F64, q1w AS F64, q2x AS F64, q2y AS F64, q2z AS F64, q2w AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_divide", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", q1x, q1y, q1z, q1w, q2x, q2y, q2z, q2w)
END SUB
SUB QuaternionLerp(q1x AS F64, q1y AS F64, q1z AS F64, q1w AS F64, q2x AS F64, q2y AS F64, q2z AS F64, q2w AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_lerp", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64,F64", q1x, q1y, q1z, q1w, q2x, q2y, q2z, q2w, amount)
END SUB
SUB QuaternionNlerp(q1x AS F64, q1y AS F64, q1z AS F64, q1w AS F64, q2x AS F64, q2y AS F64, q2z AS F64, q2w AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_nlerp", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64,F64", q1x, q1y, q1z, q1w, q2x, q2y, q2z, q2w, amount)
END SUB
SUB QuaternionSlerp(q1x AS F64, q1y AS F64, q1z AS F64, q1w AS F64, q2x AS F64, q2y AS F64, q2z AS F64, q2w AS F64, amount AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_slerp", VOID, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64,F64", q1x, q1y, q1z, q1w, q2x, q2y, q2z, q2w, amount)
END SUB
SUB QuaternionFromVector3ToVector3(fromVecx AS F64, fromVecy AS F64, fromVecz AS F64, toVecx AS F64, toVecy AS F64, toVecz AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_from_vector3_to_vector3", VOID, CDECL, "F64,F64,F64,F64,F64,F64", fromVecx, fromVecy, fromVecz, toVecx, toVecy, toVecz)
END SUB
SUB QuaternionFromMatrix(matrix AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_from_matrix", VOID, CDECL, "I32", matrix)
END SUB
FUNCTION QuaternionToMatrix(qx AS F64, qy AS F64, qz AS F64, qw AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_to_matrix", I32, CDECL, "F64,F64,F64,F64", qx, qy, qz, qw)
END FUNCTION
SUB QuaternionFromAxisAngle(axisx AS F64, axisy AS F64, axisz AS F64, angle AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_from_axis_angle", VOID, CDECL, "F64,F64,F64,F64", axisx, axisy, axisz, angle)
END SUB
SUB QuaternionFromEuler(pitch AS F64, yaw AS F64, roll AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_from_euler", VOID, CDECL, "F64,F64,F64", pitch, yaw, roll)
END SUB
SUB QuaternionToEuler(qx AS F64, qy AS F64, qz AS F64, qw AS F64)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_to_euler", VOID, CDECL, "F64,F64,F64,F64", qx, qy, qz, qw)
END SUB
SUB QuaternionTransform(qx AS F64, qy AS F64, qz AS F64, qw AS F64, matrix AS I32)
    CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_transform", VOID, CDECL, "F64,F64,F64,F64,I32", qx, qy, qz, qw, matrix)
END SUB
FUNCTION QuaternionEquals(px AS F64, py AS F64, pz AS F64, pw AS F64, qx AS F64, qy AS F64, qz AS F64, qw AS F64) AS I32
    RETURN CALL(DLL, "uxraylib.dll", "uxraylib_quaternion_equals", I32, CDECL, "F64,F64,F64,F64,F64,F64,F64,F64", px, py, pz, pw, qx, qy, qz, qw)
END FUNCTION

END NAMESPACE
