#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''
uXBasic JSON -> Browser JavaScript generator.

Input:
  --mir-json path/to/program.mir.json  (uxb-mir-module-1 or compatible)
Output:
  --out path/to/game.js

The generated JS executes MIR JSON through runtime/browser/ux_mir_executor.js.
When --wasm-manifest is supplied it loads WASM first and MIR calls can use
ux.wasm exports.
'''
from __future__ import annotations

import argparse, os, pathlib, shutil

def ensure_dir(path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

def emit_js(mir_path: pathlib.Path, out_path: pathlib.Path, wasm_manifest: str = "", mode: str = "mir-exec") -> str:
    ensure_dir(out_path)
    mir_target = out_path.parent / mir_path.name
    if mir_path.resolve() != mir_target.resolve():
        shutil.copy2(mir_path, mir_target)

    wasm_block = ""
    if wasm_manifest:
        wm = pathlib.Path(wasm_manifest)
        target_manifest = out_path.parent / wm.name
        if wm.exists() and wm.resolve() != target_manifest.resolve():
            shutil.copy2(wm, target_manifest)
        wasm_block = (
            'import { loadUxWasmFromManifest } from "./ux_wasm_bridge.js";\n'
            'try {\n'
            f'  await loadUxWasmFromManifest("./{target_manifest.name}");\n'
            f'  ux.print("WASM module yüklendi: {target_manifest.name}");\n'
            '} catch (err) {\n'
            '  ux.print("WASM yüklenemedi, JS/MIR fallback aktif: " + err.message);\n'
            '}\n'
        )

    js = f'''// Generated by uxb_json_to_js.py
import {{ ux }} from "./ux_runtime.js";
import "./ux_canvas2d.js";
import "./ux_input.js";
import "./ux_audio.js";
import "./ux_ai_bridge.js";
import "./ux_file.js";
import "./ux_serial_bluetooth.js";
import {{ runUxbMirJson }} from "./ux_mir_executor.js";
{wasm_block}

export async function main() {{
  const mir = await (await fetch("./{mir_target.name}")).json();
  await runUxbMirJson(mir, ux);
}}

main().catch(err => {{
  console.error(err);
  ux.print("uXBasic browser runtime error: " + (err && err.message ? err.message : String(err)));
}});
'''
    out_path.write_text(js, encoding="utf-8")
    return str(out_path)

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mir-json", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--wasm-manifest", default="")
    ap.add_argument("--mode", default="mir-exec")
    args = ap.parse_args()

    emit_js(pathlib.Path(args.mir_json), pathlib.Path(args.out), args.wasm_manifest, args.mode)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
