CLASS C
PUBLIC
x AS I32
END CLASS

SUB C_CTOR(self AS I32, v AS I32)
POKED self + OFFSETOF(C, "x"), v
END SUB

SUB C_DTOR(self AS I32)
POKED 9900, PEEKD(9900) + 1
END SUB

DIM p AS C = NEW C(77)
PRINT PEEKD(VARPTR(p) + OFFSETOF(C, "x"))
DELETE p
PRINT p
PRINT PEEKD(9900)
